### ISSUE TITLE
RFC: Enhancement of Existing GET API for MFE Discovery Admin API to Include Traffic Allocation Data

### ISSUE THREAD

**Issue by VelinGeorgievGP** [awslabs/frontend-discovery-service#28]
## Abstract
This RFC suggests enhancing the existing GET `/projects/{projectId}/microFrontends/{microFrontendId}/version` or introducing a new API `GET /projects/{projectId}/microFrontends/{microFrontendId}` endpoint in the MFE Discovery Admin API to include a "traffic" property in the response. This modification will enable users to retrieve traffic allocation data for different micro-frontend versions, currently a feature not available but necessary for comprehensive management and visibility in the micro-frontends deployment process.

## 1. Introduction
The proposal aims to enrich the existing GET API in the MFE Discovery Admin API to provide a more comprehensive overview of the micro-frontends, including traffic allocation information, which is critical for efficient canary release management, reporting and automation.

## 2. Background

With the Frontend Service Discovery on AWS, traffic allocation plays a significant role in the canary release strategy for micro-frontends. The current API lacks a direct method for retrieving this information, which is essential for:

- **Reporting and Monitoring**: Understanding traffic allocation is crucial for measuring the impact of new releases and for ongoing performance monitoring.

- **Automation**: Having access to traffic data through the API enables better integration with automated deployment tools, facilitating more intelligent and responsive deployment strategies.

- **Visibility**: In instances where traffic allocation is set manually, the ability to retrieve this information ensures that configurations are not forgotten or overlooked, maintaining the desired state of deployment.

The following example can allocate traffic manually: 

```
curl https://api.us-east-1.amazonaws.com/prod/projects/{projectId}/microFrontends/{microFrontendId} -H "Authorization: Bearer {Token}" -H "Content-Type: application/json" --request PATCH --data '{"name": "mfe-3","activeVersions":[{"version": "2.0.0","traffic": 50},{"version": "1.0.0","traffic": 50}]}' -H "Content-Type: application/json"
```
The above example is providing great flexibility in how we control traffic allocation, however there isn't an API to report on traffic allocation for the different microfrontends. 

I am able to see the allocation in dynamo db directly, however having this in an API will provide better integration with other services.
![image](https://github.com/awslabs/frontend-discovery-service/assets/151552404/3ba17d8a-06fb-499e-afa7-0021cf281dde)

### 3.1 API Schema Extension
Enhance GET /`projects/{projectId}/microFrontends/{microFrontendId}/versions` Endpoint
The response schema of this endpoint will be extended to include a "traffic" property for each version of the micro-frontend, detailing the percentage of traffic directed to each version.

### 3.2 Updated Response Structure

Example of the enhanced response:

```json
{
  "projectId": "ccc1673f-02aa-48cd-b82a-a7911e7150ab",
  "microFrontendId": "27a7928f-9ae2-4f6a-bc51-8478c91f7517",
  "versions": [
    {
      "url": "https://static.example.com/my-account-1.0.0.js",
      "metadata": {
        "version": "1.0.0",
        "integrity": "e0d123e5f316bef78bfdf5a008837577"
      },
      "fallbackUrl": "https://alt-cdn.com/my-account-1.0.0.js",
      "traffic": 70
    },
    {
      "url": "https://static.example.com/my-account-2.0.0.js",
      "metadata": {
        "version": "2.0.0",
        "integrity": "e0d123e5f316bef78bfdf5a008837600"
      },
      "fallbackUrl": "https://alt-cdn.com/my-account-2.0.0.js",
      "traffic": 30
    }
  ],
  "name": "my-project/catalog-123"
}
```

Example of a new endpoint implementation

`GET /projects/{projectId}/microFrontends/{microFrontendId}/traffic`
Retrieves the current traffic allocation between different versions of a specified micro-frontend.

```json
{
  "microFrontendId": "27a7928f-9ae2-4f6a-bc51-8478c91f7517",
  "trafficAllocations": [
    {
      "version": "1.0.0",
      "trafficPercentage": 70
    },
    {
      "version": "2.0.0",
      "trafficPercentage": 30
    }
  ]
}

```
### 4. Implementation Considerations

- Backward Compatibility: The enhancement should not disrupt the existing functionality of the API.
- Documentation Update: Revise API documentation to include the new property.

### 5. Security Considerations
Maintain the existing security model, ensuring that the enhanced API adheres to authorization and data privacy standards.

### 6. References
- [https://github.com/awslabs/frontend-discovery](https://github.com/awslabs/frontend-discovery)
- [https://github.com/awslabs/frontend-discovery-service/blob/main/docs/API.md](https://github.com/awslabs/frontend-discovery-service/blob/main/docs/API.md)

For visibility: @lucamezzalira  @Rody-Kirwan

**Comment by sprkem** [comment]
Hi @VelinGeorgievGP - thanks for raising this. I've discussed with Luca and agree it makes sense to include this. 

We can include this data in the `/projects/{projectId}/microFrontends/{microFrontendId}/versions` endpoint, however bearing in mind this is a paginated operation, we think it makes sense to include the traffic configuration (where applicable) in the `/projects/{projectId}/microFrontends/{microFrontendId}` endpoint. The format of this would look something like what you have suggested for `/traffic`

Hopefully this makes sense - I can look at this shortly if no concerns.
